name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Jupyter
        run: $CONDA/bin/conda install jupyter
      
      - name: Build notebooks
        run: $CONDA/bin/python .github/scripts/build_notebooks.py build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: master # The branch the action should deploy to.
          folder: . # The folder the action should deploy.